<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>SquadScout.Broker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SquadScout.Contracts\SquadScout.Contracts.csproj" />
  </ItemGroup>

</Project>
